version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/dev"
      - "/node-dev"
      - "/sre"
    schedule:
      interval: "weekly"
